### ISSUE TITLE
Release file names have changed

### ISSUE THREAD

**Issue by achaussier** [bdellegrazie/asdf-websocat#1]
Hi, thanks for your plugin.

Since 1.9.0, format of release filename has changed, example for Linux :

* Before : `websocat_amd64-linux`
* Now : `websocat_linux64`

The download URL must be updated to follow this new format, currently install of `1.9.0` release return an error :

```
asdf-websocat: Could not download https://github.com/vi/websocat/releases/download/v1.9.0/websocat_amd64-linux
asdf-websocat: An error ocurred while installing websocat 1.9.0.
```

Have a nice day

**Comment by bdellegrazie** [comment]
@achaussier thanks!

**Comment by vi** [comment]
Note: due to https://github.com/vi/websocat/issues/148, release filenames are changed again and from now on should be more stable.
